#!/usr/bin/perl -w
use strict;

=head1 NAME

cl2ver - extract version name from ChangeLog file

=head1 SYNOPSYS

  cl2ver <CHANGELOG_FILE> <VERSION_FILE>

=head1 DESCRIPTION

Extracts the date of the most recent source file modification
from CHANGELOG_FILE and writes it out to the single line file
VERSION_FILE.

=cut

my ($cl, $ver) = @ARGV;
defined $ver or die "usage: cl2ver <CHANGELOG> <VERSIONFILE>\n";

open CL, "<$cl" or die "open $cl: $!";
my $line = <CL>;
close CL;
$line =~ /^(\d\d\d\d)-(\d\d)-(\d\d) (\d\d):(\d\d)\s/ or
   die "bad changelog first line: [$line] in [$cl]";
my $version = "$1-$2-$2-$4$5";

open VERSION, ">$ver" or die "open >$ver: $!";
print VER "$version\n" or die "write to $ver: $!";
close VER or die "close $ver: $!";

