#!/usr/bin/perl -w
use strict;

use Net::FTP;

$ENV{NMS_WORKING_COPY} =~ m|^([\w\-\/\:]+)$| or die;
my $working = $1;

$ENV{NMS_SOURCEFORGE_USERNAME} =~ m|^([\w\-]+)$| or die; 
my $username = $1;

my $package = shift;
defined $package or die "usage: upload ./tarballs/<package_name>";

-r "$package.VER"    or die "$package.VER missing";
-r "$package.tar.gz" or die "$package.tar.gz missing";
-r "$package.zip"    or die "$package.zip missing";

$package =~ m|/([\w\-]+)$| or die "huh ? [$package]";
my $pkgname = $1;

system('ssh','-l',$username,'shell.sourceforge.net',"rm -f /home/groups/n/nm/nms-cgi/htdocs/v2/$pkgname.VER") and die;

system('scp',
       "$package.tar.gz",
       "$package.zip",
       "$package.VER",
       "$username\@shell.sourceforge.net:/home/groups/n/nm/nms-cgi/htdocs/v2"
      ) and die;

