=head1 NAME

=head1 SYNOPSIS

=head1 DESCRIPTION

Designed as a drop in replacement for Matt Wright's Free For all Links
script, specifically with a view to address known security and reliability
problems in that program including:

=over 1

=item Taint checking

=item Date handling

=item Locking of files

=item Checking success of file opens

=item Overwriting publicly accessible file

=back

The program also incorporates some feature and stylistic enhancements:

=over 1

=item Uses CGI.pm

=item Uses 'here documents' for printing blocks of HTML

=item Stores all link information in separate file

=item Can send mail to owner informing of new link

=back


