=head1 NAME

Frequently Asked Questions about the NMS CGI programs ( $Date: 2001-11-25 09:45:25 $ )

=head1 DESCRIPTION

This document seeks to some of the questions that people might want to ask
about the NMS project and the programs therein.

=head2 What is this NMS thing all about ?

=head2 But there are perfectly good programs already out there, why bother ?

=head2 What programs are there available in the collection ?

=head2 How are the programs licensed ?

=head2 But I have programs that do the same thing already, why change them ?

=head2 Why do you keep calling them programs and not scripts ?

=head2 Why Perl and not (Python|Tcl|Ruby) ?

=head2 Why CGI and not (PHP|ASP|Java Servlets) ?

=head2 What's with all this XML stuff ? Shouldn't the programs output HTML ?

=head2 What's this $emulate_matts_code thing all about ?

=head2 I've heard that C<use strict;> is gay ..

=head2 Why don't the programs decode the parameters like other PERL programs ?

=head2 Why don't you use C<cgi-lib.pl> like everyone else does ?

=head2 But isn't the CGI module terribly big and slow ?

=head2 What's with all this C<die> stuff all over the programs ?

=head2 Isn't C<flock> something that sheep do ?


